version: '3.8'

services:
  app:
    build:
      context: ./backend
    image: my-laravel-app
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: nutri
      DB_USERNAME: root
      DB_PASSWORD: "123"  # Fixed: wrapped in quotes, removed backtick
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    image: my-react-app
    ports:
      - "3000:80"
    depends_on:
      - app
    environment:
      REACT_APP_API_URL: "http://localhost:8000"
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nutri
      MYSQL_ROOT_PASSWORD: "123"  # Fixed
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my_nutri_data.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge

